### ISSUE TITLE
not log level less than INFO

### ISSUE THREAD

**Issue by achimwessling** [Ritzlgrmft/ionic-logging-sample#1]
Hi,

I'd like to use your lib, but I get no log to work with a level below INFO.

I use this configuration with ionicconfiguration service:
```
{
  "secret": "Pst!",
  "logging": {
    "logLevels": [{
        "loggerName": "root",
        "logLevel": "ALL"
      },
      {
        "loggerName": "gcm.foo",
        "logLevel": "OFF"
      }
    ]
  }
}
```
The result of the following code
```
this.logger.trace(' ... trace log');
this.logger.debug("  ... debug log");
this.logger.info("   ... info log");
this.logger.warn("    ... warn log");
this.logger.error("     ... error log");
this.logger.fatal("      ... fatal log");
```

looks like this:

[app-scripts] [22:24:50]  console.info: 22:24:50,609 gcm.provider.storage ... info log
[app-scripts] [22:24:50]  console.warn: 22:24:50,610 gcm.provider.storage ... warn log
[app-scripts] [22:24:50]  console.error: 22:24:50,610 gcm.provider.storage ... error log
[app-scripts] [22:24:50]  console.error: 22:24:50,610 gcm.provider.storage ... fatal log

I could reduce the log level and set it for example to ERROR! This works! Could you please give any hint.

THANKS a lot!

**Comment by Ritzlgrmft** [comment]
In general, also `debug` logs are working. However, if you see them depends on your console.

Par example, in Chrome the default log levels for the console do not include `Verbose`. Which means, `debug` logs are not shown. As soon as you switch to all levels, you see also `debug` logs.

I assume, you have a similar problem in ionic's console logs. I check in the dev tools, so the debug statement is send to the server. But there it gets ignored.

BTW: if you are using the `BrowserConsoleAppender`, the debug log is written with `console.debug()`. So I am pretty sure that you will see the same behaviour if you use `console.debug()` directly.

**Comment by achimwessling** [comment]
Thanks for your reply! You are right! If I switch on the verbose level in Chrome console I also get the debug messages.
Now I'm only missing the trace level! I found no possibility to make TRACE level at any point visible! Do you know one?

Thanks!

**Comment by Ritzlgrmft** [comment]
@achimwessling: The `BrowserConsoleAppender` uses a default threshold of `DEBUG`. That's the reason why you do not see `TRACE` messages.

If you set the `threshold` during configuration to `ALL`, you will see also the `TRACE` messages.

The configuration were:

```json
{
  browserConsoleAppender: {
    threshold: "ALL",
  }
}
```
